/**
 * Consent-ledger service contract — append-only ledger for registration consent.
 *
 * Records each subject's (org or coordinator/aggregator) acceptance of the
 * Terms of Service and Privacy Policy at registration time. The table is
 * keyed by `subject_type` + `subject_id` so one ledger serves both
 * registration flows without foreign-key coupling.
 *
 * Every method returns `Result<T, BaseError>` — never throws across the
 * service boundary.
 *
 * @module @aggregator-dpg/consent-ledger/interface
 */

import { z } from 'zod';
import type { BaseError } from '@aggregator-dpg/shared-primitives/errors';
import type { Result } from '@aggregator-dpg/shared-primitives/result';

// ─── Zod schemas ─────────────────────────────────────────────────────────────

/**
 * Input schema for recording a single registration-consent acceptance.
 *
 * `subjectType` discriminates between an org registration (`'org'`) and a
 * coordinator/aggregator registration (`'aggregator'`).
 */
export const RecordConsentInputSchema = z.object({
  /** Discriminator: `'org'` maps to `aggregator_orgs.id`; `'aggregator'` to `aggregators.id`. */
  subjectType: z.enum(['org', 'aggregator']),
  /** UUID of the subject row that accepted the terms. */
  subjectId: z.string().uuid(),
  /** Signal Stack network identifier (e.g. `blue_dot`). */
  network: z.string().min(1),
  /** Optional per-brand variant; null/undefined when using the network default. */
  brand: z.string().min(1).nullish(),
  /** Version of the Terms of Service document accepted. */
  termsVersion: z.number().int().min(1),
  /** Version of the Privacy Policy document accepted. */
  privacyVersion: z.number().int().min(1),
  /**
   * How consent was captured. Defaults to `'registration'` when omitted.
   * The bulk-upload operator attestation encodes the upload + statement
   * version here, e.g. `bulk_upload:<uploadId>:v1` (no dedicated column).
   */
  source: z.string().min(1).optional(),
});

/** TypeScript type inferred from {@link RecordConsentInputSchema}. */
export type RecordConsentInput = z.infer<typeof RecordConsentInputSchema>;

/**
 * Schema for a persisted consent record row, as returned after a successful
 * insert.
 *
 * Field names mirror the Drizzle-inferred `AggregatorConsentRecord` type from
 * `@aggregator-dpg/db-schema` but are declared here independently so the
 * interface file stays free of heavy deps.
 */
export const ConsentRecordSchema = z.object({
  /** Surrogate primary key; UUID generated by Postgres. */
  id: z.string().uuid(),
  /** Discriminator: `'org'` or `'aggregator'`. */
  subjectType: z.string(),
  /** UUID of the subject row. */
  subjectId: z.string().uuid(),
  /** Version of the Terms of Service accepted. */
  termsVersion: z.number().int().min(1),
  /** Version of the Privacy Policy accepted. */
  privacyVersion: z.number().int().min(1),
  /** Signal Stack network identifier. */
  network: z.string(),
  /** Per-brand variant, or null for the network default. */
  brand: z.string().nullable(),
  /** How consent was captured — `'registration'` in v1. */
  source: z.string(),
  /** Server-stamped moment the registrant checked the consent checkbox. */
  acceptedAt: z.date(),
  /** Row-creation timestamp; set by Postgres on INSERT. */
  createdAt: z.date(),
});

/** TypeScript type inferred from {@link ConsentRecordSchema}. */
export type ConsentRecord = z.infer<typeof ConsentRecordSchema>;

// ─── Abstract base class ─────────────────────────────────────────────────────

/**
 * Persistence port for the append-only `aggregator_consent_record` ledger.
 *
 * Implementations:
 *   - Postgres: real Drizzle-backed INSERT into `aggregator_consent_record`.
 *   - InMemory: Map-backed for unit tests within this package.
 *   - Fake: in-memory + `seed()` / `buildConsentRecord()` helpers for
 *     cross-package consumer tests.
 */
export abstract class ConsentLedgerBase {
  /**
   * Appends one consent record for the given subject.
   *
   * The `source` field defaults to `'registration'` when the input omits it;
   * `acceptedAt` is server-stamped at write time.
   *
   * @param input - Validated consent payload.
   * @returns `ok(ConsentRecord)` on successful insert; `err(BaseError)` on
   *   validation failure or DB/upstream error.
   */
  abstract recordRegistrationConsent(
    input: RecordConsentInput,
  ): Promise<Result<ConsentRecord, BaseError>>;
}
